name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  maven-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Test
        uses: ./.github/actions/maven-test